Repository mooore-digital/magento2-module-wordpress-integration-cms, pull requests merged in 2022-01, with the labels that each got.

#62 IMP: Sometimes double-dashes gets encoded to one from API
  Plugin/Model/PagePlugin.php
Labels: bug

#66 ADD: noroute to list of layouts to skip
  CHANGELOG.md
  Observer/LayoutLoadBefore.php
Labels: enhancement, question, In Progress

#69 Develop
  CHANGELOG.md
  Observer/LayoutLoadBefore.php
  etc/adminhtml/di.xml
  etc/adminhtml/events.xml
  etc/adminhtml/system.xml
  etc/config.xml
  etc/db_schema.xml
  etc/frontend/di.xml
  etc/frontend/events.xml
  etc/module.xml
  registration.php
  view/adminhtml/ui_component/cms_page_form.xml
  view/adminhtml/web/js/components/select-site.js
  view/adminhtml/web/template/ui/grid/filters/elements/ui-select.html
  view/frontend/layout/cms_wp_content.xml
  view/frontend/page_layout/1column-wp.xml
Labels: Release
